# Generated by Django 3.1.7 on 2021-02-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GTCStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200, unique=True)),
                ('mail', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('demand', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('current_company', models.CharField(max_length=200)),
                ('interest', models.CharField(choices=[('not interested', 'not interested'), ('expecting more', 'expecting more'), ('comfortable', 'comfortable')], max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('job_profile', models.CharField(max_length=200)),
            ],
        ),
    ]
